name: Combine Chapters

on:
  push:
    paths:
      - '*.md'
  workflow_dispatch:

jobs:
  stitch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}  # Explicitly use the default token

      - name: Stitch Markdown files
        uses: abhinav/stitchmd-action@v1
        with:
          mode: write
          summary: summary.md
          output: End-of-Conflict-All-in-1-Chapters.md

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add End-of-Conflict-All-in-1-Chapters.md
          git diff --staged --quiet && echo "No changes detected" && exit 0
          git commit -m "Auto-update combined chapters"
          git push origin HEAD:main
